### ISSUE TITLE
Error on null results

### ISSUE THREAD

**Issue by buzzkc** [fewieden/MMM-NFL#29]
I've been having an issue with MM crashing and the last set of error logs indicated that the results were null on line 56 of node_helper.js

I've updated my node_helper.js on line 56 to check for null

this:
`} else if (Object.prototype.hasOwnProperty.call(result, 'ss')) {`

to this:
`} else if (results && Object.prototype.hasOwnProperty.call(result, 'ss')) {`

I'm still testing the change, but will report back if it resolved the MM app from crashing.

**Comment by buzzkc** [comment]
It seems once the new weeks data is being posted, there is an error getting data. I didn't get an error for the results this time, but for gsis...

`
TypeError: Cannot read property 'gsis' of null
    at Class.setMode (/home/pi/MagicMirror/modules/MMM-NFL/node_helper.js:138:26)
    at parser (/home/pi/MagicMirror/modules/MMM-NFL/node_helper.js:59:30)
    at Parser.<anonymous> (/home/pi/MagicMirror/modules/MMM-NFL/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.onclosetag (/home/pi/MagicMirror/modules/MMM-NFL/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/pi/MagicMirror/modules/MMM-NFL/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/pi/MagicMirror/modules/MMM-NFL/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/pi/MagicMirror/modules/MMM-NFL/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/pi/MagicMirror/modules/MMM-NFL/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/home/pi/MagicMirror/modules/MMM-NFL/node_modules/xml2js/lib/parser.js:322:31)
`
